### ISSUE TITLE
ModNation Racers sceNpCommerce2GetCategoryInfo crash

### ISSUE THREAD

**Issue by derole1** [RipleyTom/rpcn#11]
Hello, I have been attempting to create a server for ModNation racers recently but have run into a roadblock when using ModNation racers + latest DLC with RPCN. It seems the game crashes with the last function on the thread that had caused the crash being "sceNpCommerce2GetCategoryInfo". I assume the game is trying to confirm DLC ownership status with RPCN?

The error logged by RPCS3 is "F {PPU[0x1000012] Thread (CommerceManagerThread) [0x00519248]} VM: Access violation reading location 0x3c (unmapped memory) [type=u0]"

How to reproduce:
- Obtain ModNation Racers BCUS98167 + The latest DLC (Note this issue does not occur with the base game)
- Launch game with RPCN enabled, wait for server timeout
- Attempt to do anything from the title screen, it will crash just before the loading screen transitions in

I think this is the correct repository to report to but sorry if it isn't. Thank you.

**Comment by TorutheRedFox** [comment]
LittleBigPlanet games also do this if online, which in the case of LBP1, makes playing DLC levels impossible (and the extra levels if you have the GOTY edition)

although it's not as bad, as you can simply avoid going to the store in LBP2 and 3 as DLC levels there have their own section that doesn't access PSN (unless you press square on a polaroid then it will crash as it tries to load a description from the PlayStation Store)

**Comment by RipleyTom** [comment]
Added a hack in rpcs3 so it shouldn't crash anymore.
Fixed in https://github.com/RPCS3/rpcs3/pull/15041.
