### ISSUE TITLE
API for getting user information?

### ISSUE THREAD

**Issue by TorutheRedFox** [RipleyTom/rpcn#26]
getting certain information on a given user can be useful for private servers, as a few games rely on the server to know who your friends are to return their scores, allow you to invite them to your room or ask to join theirs, etc.

(btw those examples are all from LBP lol)

**Comment by RipleyTom** [comment]
I think the only interaction between psn/rpcn and 3rd party servers is the ticket, the client probably gives the friendlist to the server. There may be an issue with some of the implementation of those api but I don't think an api for servers is warranted.

**Comment by TorutheRedFox** [comment]
the client doesn't give the friendlist to the server, I checked the logs

the game expects the server to already know this information
