### ISSUE TITLE
Provide example certificates and private keys for development  

### ISSUE THREAD

**Issue by Waelwindows** [RipleyTom/rpcn#3]
It's hard to debug/develop currently as the program immediately quits due to the missing certificates and/or private key.
It would be helpful if you provide an example certificate/private key or give instructions on how to create them

Affects #1 and #2

**Comment by RipleyTom** [comment]
I added a brief explanation for it( https://github.com/RipleyTom/rpcn/commit/7a90d2a207331e252c21a0b4ec3ed7bc84732728 ).
