### ISSUE TITLE
Crash in Windows using the latest version

### ISSUE THREAD

**Issue by JumpingY** [RipleyTom/rpcn#59]
thread 'main' has overflowed its stack
![QQ截图20240108135734](https://github.com/RipleyTom/rpcn/assets/54348327/b89ace18-5348-49c2-aa96-1b03c25bfcf3)

**Comment by JumpingY** [comment]
v0.7.6 is OK.This issue occurs in versions after v0.7.6

**Comment by RipleyTom** [comment]
Fixed on https://github.com/RipleyTom/rpcn/releases/tag/0.9.2
