### ISSUE TITLE
[Q] use on a real PS3 with CFW

### ISSUE THREAD

**Issue by eadmaster** [RipleyTom/rpcn#65]
can this be used on a real PS3 with CFW?

**Comment by RipleyTom** [comment]
No and it most likely never will, sorry.

**Comment by eadmaster** [comment]
nevermind, i've found [this project that works even on real PS3s](https://psone.online/) (and [this](https://psone.online/faq)).

I think it would be a good idea sharing servers for easier casual matchmaking when possible.

**Comment by RipleyTom** [comment]
RPCN emulates the PSN part of matchmaking.
PSONE is private servers for specific games(which will work on both ps3 and rpcs3).

They are not the same thing...

**Comment by TiZmSpectrum** [comment]
To the devs, look into getting in contact with CHC from the Openspy project.
He's been working on a replacement psn server for real ps3's not sure if any of you are interested in maybe combining both efforts for the ultimate network!
