### ISSUE TITLE
Email not sent

### ISSUE THREAD

**Issue by neishwang** [RipleyTom/rpcn#84]
Hello,
I tried to retrieve my old account Token, but I didn't receive any mail
so I tried to create a new one, and same I don't receive anything
For my last test I used a gmail address, and my old account was from a mail where I already receive a mail in 2022

Can you help me ?

**Comment by RipleyTom** [comment]
There can be sporadic failures from the email server, try again tomorrow would be my advice

**Comment by neishwang** [comment]
Unfortunately, I still don't recieve anything :(
Should I wait more than a day ?
