### ISSUE TITLE
Email still not sent

### ISSUE THREAD

**Issue by neishwang** [RipleyTom/rpcn#85]
Hello,
sorry to open another issue, but I can't re-open the closed one.
I tried again to send token email and I still don't recieve it (even in spam folder in case of)

Is it possible to check if the mail server tried to send it ?
I'm using a "@free.fr" (French ISP) in 2022 I succeed to recieve the token, but today is not working.
I also tried to create an account with a "@gmail.com" mail, and stil have nothing recieved
(Maybe you may delete some of the account created ... to test)

Or Should I wait more than a day, perhaps ?

Thank you

**Comment by RipleyTom** [comment]
I managed to resend my token without issues to my gmail account. I looked in the logs and I see no error sending to a free.fr account either.

If you require further support, please use the rpcs3 discord.
