### ISSUE TITLE
The games loading screen freezes when using network rpcn1.3.0

### ISSUE THREAD

**Issue by JumpingY** [RipleyTom/rpcn#89]
I tested two games,E.X. Troopers [NPJB00235] and LostPlanet 2 [MRTC00002],In previous versions of the emulator( 0.0.33-16932 earlier versions), they worked fine on RPCN 1.2.4，However, after updating RPCN 1.3.0, this problem occurred.They can only be played in the latest RPCS3 version if you disable the network.
In addition, I have tested other games (Dragon's Crown [BCAS20298],機動戦士ガンダム エクストリームバーサス フルブースト [NPJB00512],SF3: Online Edition [NPEB00554]) in the latest RPCS3 and there seems to be no problem with the network.

![QQ20240922-104508](https://github.com/user-attachments/assets/4b62f527-b374-494d-963d-5d274e5b3851)
![QQ20240922-104329](https://github.com/user-attachments/assets/48192d88-bba4-401d-9e04-e209e0dce8a1)

[RPCS3-MRTC00002.log.gz](https://github.com/user-attachments/files/17088090/RPCS3-MRTC00002.log.gz)
[RPCS3-NPJB00235.log.gz](https://github.com/user-attachments/files/17088091/RPCS3-NPJB00235.log.gz)

**Comment by RipleyTom** [comment]
I ran BLJM60528 (Extroopers) online with no issues here.
I also see no communication error with the server or even, in the case of E.X.Troopers any server commands issued in your log which makes me think it's probably not RPCN related.

**Comment by RipleyTom** [comment]
Someone on RPCS3's team also tested MRTC00002 (Lost Planet 2) and it also works for them.

**Comment by JumpingY** [comment]
> Someone on RPCS3's team also tested MRTC00002 (Lost Planet 2) and it also works for them.

Thank you. I will check the rpcs3 settings again and it seems to be my own problem and close this issue
