### ISSUE TITLE
Demon's Souls: Infinite Loading Screen / Unable to leave on failed invasions.

### ISSUE THREAD

**Issue by Lil-Sassy** [RipleyTom/rpcn#9]
## Quick summary
When an invader fails to establish a connection. Your game will say 'Unable to leave during multiplayer session' indefinitely when trying to use an archstone. Must go to Quit Game then on the next loading screen it will be stuck there permanently. Rebooting the game resumes normal loading screen behavior. 

## Details

Easiest to replicate at 3-3 with the Old Monk fight. If for whatever reason the invader is unable to establish a connection, the game will allow you to quit to main menu but you cannot use an archstone to leave. Summoning never has this problem, can only replicate this by having someone invade. A successful invasion and death of either the host or the invader will NOT cause the problem to manifest.

Unable to determine what causes the invasion failure. 

Unrelated to issue #8 

#### 4. Please provide comparison with real PS3.
Never occurs.

#### 5. Please provide your system configuration:
* RPCS3 v0.0.12-10910-34eff440 Alpha
* OS: Windows 10
* CPU: Intel Core i9-9900K
* GPU: GeForce RTX 2080 Ti 
* Driver version: 456.38
* 63.93 GiB RAM

**Comment by luigibrancati** [comment]
This happens to me as well, as soon as invasion fails I can't go back to the nexus neither with the archstone nor with the Evacuate miracle, and of course I can't try to invade again. Also, I can't use the Blue eye stones to leave my sign for co-op.

The rest is as @Lil-Sassy said, after quitting to the main menu and reloading the game, everything turns to normal.

5. Please provide your system configuration (this is a laptop computer):
    RPCS3 v0.0.13-11265-28cbba5a Alpha
    OS: Windows 10
    CPU: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz   2.59 GHz
    GPU: NVIDIA GeForce GTX 950M
    Driver version: 457.30
    8.00 GiB RAM

**Comment by RipleyTom** [comment]
I'll assume this is fixed.
