### ISSUE TITLE
Call of Duty®: Black Ops II (NPUB31054)

### ISSUE THREAD

**Issue by Xeddius** [RipleyTom/rpcn#95]
RPCN logs in successfully, however the LAN mode does not show lobbies, and online functions are obviously non-functional.
If there's any way I can help get LAN working with this game that'd be phenomenal.
Here is the relevant log from RPCN:

```
 INFO {npid=user1}: rpcn::server::client: Parsing command Some(RequestTicket)
 INFO {npid=user1}: rpcn::server::client::cmd_misc: Requested a ticket for <UP0002-BLUS31011_00>
 INFO {npid=user1}: rpcn::server::client: Succeeded with NoError
```

**Comment by RipleyTom** [comment]
RPCN is emulating PSN matchmaking so it's irrelevant to any LAN mode.
